spring.application.name=ms-eureka-server
server.port=8761

# No queremos que el servidor se busque a s� mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Para que no te llene la consola de logs innecesarios en la 3.5.x
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN