server.port=8080
spring.application.name=ms-gateway

# Registro en Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# --- CONFIGURACI�N DE RUTAS ---

# 1. Ruta para MS-USUARIOS
spring.cloud.gateway.routes[0].id=ms-usuarios
spring.cloud.gateway.routes[0].uri=lb://MS-USUARIOS
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/usuarios/**

# 2. Ruta para MS-PRODUCTOS (V2)
spring.cloud.gateway.routes[1].id=ms-productos
spring.cloud.gateway.routes[1].uri=lb://MS-PRODUCTOS
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v2/**

# 3. Ruta para MS-SEGURIDAD (La que ya ten�as)
spring.cloud.gateway.routes[2].id=ms-seguridad
spring.cloud.gateway.routes[2].uri=lb://MS-SEGURIDAD
spring.cloud.gateway.routes[2].predicates[0]=Path=/auth/**

# Ruta para el Microservicio de Pagos
spring.cloud.gateway.routes[3].id=ms-pagos
spring.cloud.gateway.routes[3].uri=lb://MS-PAGOS
spring.cloud.gateway.routes[3].predicates[0]=Path=/pagos/**

spring.cloud.gateway.routes[4].id=ms-sucursales
spring.cloud.gateway.routes[4].uri=lb://MS-SUCURSALES
spring.cloud.gateway.routes[4].predicates[0]=Path=/sucursales/**

spring.cloud.gateway.routes[5].id=ms-pedidos
spring.cloud.gateway.routes[5].uri=lb://MS-PEDIDOS
spring.cloud.gateway.routes[5].predicates[0]=Path=/api/v1/pedidos/**

spring.cloud.gateway.routes[6].id=ms-inventario
spring.cloud.gateway.routes[6].uri=lb://MS-INVENTARIO
spring.cloud.gateway.routes[6].predicates[0]=Path=/productos/**

spring.cloud.gateway.routes[7].id=ms-delivery
spring.cloud.gateway.routes[7].uri=lb://MS-DELIVERY
spring.cloud.gateway.routes[7].predicates[0]=Path=/delivery/**